package com.rei.javaDemo.utils;

import cn.hutool.core.codec.Base64;
import cn.hutool.core.util.CharsetUtil;
import cn.hutool.core.util.RandomUtil;
import cn.hutool.core.util.StrUtil;
import cn.hutool.crypto.SecureUtil;
import cn.hutool.crypto.asymmetric.KeyType;
import cn.hutool.crypto.asymmetric.RSA;

import java.io.UnsupportedEncodingException;
import java.nio.charset.Charset;
import java.security.KeyPair;

/**
 * 加密工具类
 * @date 2020年7月17日15:45:29
 */
public class EncryptionUtil {

    /**
     * RSA加密
     * @param str 要加密的字符串
     * @param publicKey 公钥
     * @return 加密过后的字符串base64形式的
     */
    public static String encryptRSA(String str,String publicKey){
        RSA rsa = new RSA(null,publicKey);
        byte[] encrypt = rsa.encrypt(StrUtil.bytes(str, CharsetUtil.CHARSET_UTF_8), KeyType.PublicKey);
        return  Base64.encode(encrypt);
    }

    /**
     * RSA解密
     * @param str 要解密的字符串
     * @param privateKey 私钥
     * @return 解密后的字符串
     */
    public static String decryptRSA(String str,String privateKey){
        RSA rsa = new RSA(privateKey,null);
        byte[] decrypt = rsa.decrypt(str, KeyType.PrivateKey);
        try {
            return new String(decrypt, "UTF-8");
        }catch (UnsupportedEncodingException e){
            e.printStackTrace();
        }
        return null;
    }

    public static void main(String[] args) {

        RandomUtil.getRandom();
        String privateKetStr = "MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAI3qfdFfp0Sm6YtQc8kUuZKFZbqDxvVzmHET0bmmBL85DRZS2qiG8NnfFnXXMT2R5PBOg7zgCJaZaLUxrnFEPOtRLQFP4e+r7KQWHErtSXfDwNHJlOnIWtH/146n8z71915fb2KrYVq7pgNS7eqNhWR9saelrLGOG6YhWYEurlxpAgMBAAECgYABINEZPgJtaEpJAj25ZoHHKWpSnkORpfabR4YOTMSS5Jg3CjeUyWXWxZA/JZPNooBIbMddVAadc+DCN//kBJ/bWABbDivBP7QgJD0peih3FXjLX+0yB2ugwV/N3Lh6FpndEhxAyO1nggjb3iZ8JpLd33Hq0vul6FLXtayifKRvAQJBANS6HhfeaIeWEZm4OcIEMl2wlxS0NLsKe+aiBIRriwOeDpydO91oHFP+hUmNY9AIqyhOEibUUsGQl15t9aaPWOECQQCqyNkh/uY9tH+ikWl1ANpQAwm1Fsdr0vPTKSOtb7hUpSSIrlVlOGppcIH2iC3GUr0cfnoHNkY+qYF8fGr3NUyJAkEAti+wFkEkxPqBmGVvEfsGJ7dVrSWpA4e3FY8szzxLko2LdhYzbyv7FvSkspmlIkZKT/qNETRGrABpozYJbNzYAQJAOzo8UxXbMzsNqItVT0Zkb6seCrdDoZkfBfQWc2dzPaen697JrrjJ7pcd+ylu9oBrJR6XozinU8PlLA7Z6bGKQQJBAK8o50n/c1vi3jKjOaEjb3tJsGwuNXdOZIxAlAy0IntMZC0mAs1TAkBuxl+6YhyFoCTY8cBJ7EUg8hH6eDzNWIQ=";
        String publicKeyStr = "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCN6n3RX6dEpumLUHPJFLmShWW6g8b1c5hxE9G5pgS/OQ0WUtqohvDZ3xZ11zE9keTwToO84AiWmWi1Ma5xRDzrUS0BT+Hvq+ykFhxK7Ul3w8DRyZTpyFrR/9eOp/M+9fdeX29iq2Fau6YDUu3qjYVkfbGnpayxjhumIVmBLq5caQIDAQAB";

        String str = "我是谁我是谁我是谁我是谁我是谁我是谁我是我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我我是谁我是谁我是谁我是谁我是谁我谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁我是谁";
        String jiami = encryptRSA(str,publicKeyStr);
        System.out.println(jiami);
        String jiamiStr = "6765fef2b6ac2d59058d0a4cb1288d3a65deed019374663b0a20a0aa25ccefebd0b7cfb1315bd91e66f2060f9eb2661912a7deec92923787a986f7b0d8431d0bb0f0be34a3ae89dc2d3057f5eabfe05180f1e876c05e827ac59ea977c2e0dbf3851a9346b7e3b27113fda9517457fe4ff396843a8faa3227ed5bfb86d2318637";
        String jiemi = decryptRSA(jiami,privateKetStr);
        System.out.println(jiemi);
    }
}
